### ISSUE TITLE
Create homepage

### ISSUE THREAD

**Issue by SylvainRamseyer** [HE-Arc/lenspector#2]

**Comment by groovytron** [comment]
@SylvainRamseyer  et @axelroy pouvez-vous valider la page d'accueil? Cela fonctionne-t-il chez vous aussi? Niveau design ça vous va?
Normalement, on devrait pouvoir utiliser le même template pour l'index de l'inventaire et éventuellement des commandes.
commit: 3915c1edf81b3a7d609279c53190b3efce76365d

**Comment by greut** [comment]
:cry: http://lenspector.srvz-webapp.he-arc.ch/ ref #1

**Comment by axelroy** [comment]
Déploiement à venir. J'ai regardé pour la page d'accueil, il me semble qu'il manque une entrée dans le menu, sinon tout est en ordre. J'ai directement crée une révision et une pull request, vous pouvez accepter ou refuser suivant votre avis.

https://github.com/HE-Arc/lenspector/pull/15

**Comment by groovytron** [comment]
Ne soyez pas triste @greut. C'est déployé! Par contre c'est normal que le chargement d'une page prenne 1min20? Je n'ai rien changé à part `root /var/www/public/lenspector/public;` dans le fichier `/etc/nginx/sites-enabled/lenspector`. J'ai ensuite rechargé le fichier de config avec `nginx -s reload`.
Le projet a été simplement cloné avec git en HTTPS dans `/var/www/public/lenspector`.
L'utilisateur de nginx (`www-data`)a les droit en lecture/écriture/exécution dans les dossiers `bootstrap/cache` et `storage` du projet.
Tout fonctionne. C'est juste que c'est un peu lent.
Merci d'avance pour votre réponse et bon weekend.

**Comment by groovytron** [comment]
Je retire ce que j'ai dit. Je crois qu'en fait c'est parce que j'étais encore dans le VPN de l'école quand j'ai voulu tester. Hors VPN ça fonctionne tip top. Merci encore ces serveurs. C'est top.

**Comment by greut** [comment]
Oui, ce VPN ne nous aide en rien... bon boulot. :+1:

**Comment by groovytron** [comment]
@SylvainRamseyer  et @axelroy, peut-on considérer cette issue comme résolue?

**Comment by axelroy** [comment]
@groovytron Oui c'est ok pour moi.
