### ISSUE TITLE
Table HTML

### ISSUE THREAD

**Issue by greut** [HE-Arc/lenspector#61]
Je vous invite à lire prendre exemple sur l'article suivant afin de créer des tables HTML accessibles.

> _Tables without structural markup to differentiate and properly link between header and data cells, create accessibility barriers. Relying on visual cues alone is not sufficient to create an accessible table. With structural markup, headers and data cells can be programmatically determined by software [...]_
>
> https://www.w3.org/WAI/tutorials/tables/

**Comment by groovytron** [comment]
Quand vous dites *accessibles*, vous entendez accessible aux personnes malvoyantes? La proposition que je retiens serait [celle-ci](https://www.w3.org/WAI/tutorials/tables/one-header/#table-with-ambiguous-data). Cependant, elle propose d'utiliser l'attribut `scope` qui n'est [plus supporté en HTML5](http://www.w3schools.com/tags/att_td_scope.asp).
Un autre solution serait de grouper les headers dans un `<thead>` et mettre les données dans un `<tbody>` mais je ne sais pas si ça répond à ce que vous demandez.

**Comment by greut** [comment]
> The `<td>` scope attribute is not supported in HTML5.

Mais `<th scope>` ne pose pas de problème, au contraire.

> The `th` element may have a scope content attribute specified.
>
> https://www.w3.org/TR/2016/REC-html51-20161101/tabular-data.html#element-attrdef-th-scope

`thead` et `tbodỳ` ne sont pas utilisés dans les exemples du WAI car ils n'ont pas d'influence sur l'accessibilité des données. thead, tfoot servent à avoir une mise en page correcte à l'impression.

En l'absence de `tbody`, il est créé automatiquement par le moteur HTML.

Exemple : https://jsfiddle.net/greut/yoxcebn3/

Ce qui est une grande différence en HTML et XHTML (servi en tant que `application/xhtml+xml`). D'où ma recommendation générale de ne pas faire de XHTML, jamais.
